### PR TITLE
Myriad Improvements

### PR DESCRIPTION
**Pull request by andrewchawk**
Really, I just improved the wording and formatting and converted the document to a literate Agda LaTeX file.

The upside is readability.
The downside is that, at least on my system, literally every line is now credited to me.  :-)

As ever, feel free to delete any changes which you dislike.

### CODE REVIEW

**Comment by onestruggler** [comment]
no worries at all. as long as it's improvement for others, i don't care credit at all. all my knowledge comes from the open source, it's nice to give something back, which others like you like and want to make it better.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: andrewchawk ***@***.***>
Sent: Tuesday, August 13, 2024 10:57:44 PM
To: onestruggler/short-intro-reflection ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [onestruggler/short-intro-reflection] Myriad Improvements (PR #4)

CAUTION: The Sender of this email is not from within Dalhousie.

Really, I just improved the wording and formatting and converted the document to a literate Agda LaTeX file.

The upside is readability.
The downside is that, at least on my system, literally every line is now credited to me. :-)

As ever, feel free to delete any changes which you dislike.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/onestruggler/short-intro-reflection/pull/4

Commit Summary

  *   e141623<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/e1416238e50971bf4109ece723c8c19352ed2d0a> I deleted some *seemingly*-redundant spaces.
  *   cb72150<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/cb72150de18afe2d8c3b2a0d654f45bb0338be84> I tried to improve the formatting.
  *   04ea515<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/04ea5155995b79377a49641b21b38c0ec1b0e493> I broke up some long lines.
  *   49e2b2d<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/49e2b2d85d3b5ece4741e1b5014670321376c94f> I reformatted a definition in the style of Haskell's formatting for long lists.
  *   3c5d4cc<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/3c5d4cca919cc9cf3b898daeaad914b213fadafa> I got rid of some unneeded hidden arguments.
  *   cd587b8<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/cd587b8c952b6ff03534362b56e4f422641f5f1c> I joined some sentence fragments into a single sentence. I did have to change the method of emphasis a bit, though.
  *   7c2ddec<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/7c2ddec9a095fddae6c302a52cf7b5d2e0effb0b> I added some spaces to increase overall consistency in formatting.
  *   458570f<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/458570f005b2e6ff1b0cd62b6d257ebcab93868e> I corrected some misspellings.
  *   92adcb0<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/92adcb0bfcecdb618dcf57db8d2f766a659f0d87> I rewrote a sentence. The change might be subjective, though.
  *   5177083<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/5177083f413eaff241c5f736826d857c02128f72> I think that this change improves skimmability.
  *   b088a84<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/b088a843cc394f1e5aa0471fbed859f6bb8ba030> I junked an "always". From experience, I know that some conversions can be pretty difficult.
  *   43b15aa<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/43b15aa6886d618941e3221328d9480b952c3e01> I shrank a line.
  *   6b25042<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/6b2504222cd9f05109107e70411c25dc3445d4d2> I made myriad assorted documentation improvements.
  *   ab71c3f<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/ab71c3fd775e077417f386a665e65a2b57b265a7> I made myriad wording improvements.
  *   196e3b4<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/196e3b4e96b301bdb696f95a399d95bac37fb26b> I combined two words in a pseudo-type-signature. Semantically, "arithmetic expression" is kind of interesting, but I think that "ArithmeticExpression" is more straightforward. :-)
  *   e638b42<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/e638b422ce4a0362491555df0ec16c3a7ce7bdc8> I fixed up a comma splice.
  *   4923f3e<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/4923f3e0724ac367b9970d5534298edd412a428b> I made some general readability-related improvements.
  *   477e187<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/477e18768ed5f058d69cb1a02a59c6e287315e80> I tried to grammatically fix up a sentence, but I *may* have lost some of the tone of the original sentence.
  *   54f7a63<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/54f7a637043e33ec5d802241137f4eb400051a47> I applied a bunch of tiny changes to a single paragraph.
  *   0beabed<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/0beabed2c5817020bb817d01b361bbe047b31201> I replaced some assumption-related sentences with definition-related sentences.
  *   a4101ce<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/a4101cea99f2fec251fcb4c0c98cee43d7c3d7a0> I added a "then" and fixed some typos.
  *   576757b<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/576757ba1eef543275a9e0dce74f02bd6ffc61fa> I fixed up a sentence.
  *   24a0523<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/24a05231333ac13274861df5939d16b99687bc43> Revert "I combined two words in a pseudo-type-signature. Semantically, "arithmetic expression" is kind of interesting, but I think that "ArithmeticExpression" is more straightforward. :-)"
  *   f304c49<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/f304c49b6f00c5ba46b521cc522ce576f9d34e57> So begins the LaTeXification.
  *   1ec9f96<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/1ec9f96789de8cecd4e27038df420954861db4b3> I converted a one-line list into a multi-line list and made some minor wording improvements.
  *   cb571cd<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/cb571cd7179281854818ec6c5283e27f59db4007> I capitalized "Agda".
  *   8b7e96e<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/8b7e96e8b9059e5fea6b2ce2fabcc652e8ab195c> I tried to improve the readability of a segment.
  *   58ad553<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/58ad55312279aa08a8c94053d9b9c28a81709b70> I made some minor wording improvements.
  *   efcbadc<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/efcbadcb4a048ceb311f052b2a0ec706157386da> I issued a typo fix.
  *   8bd0919<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/8bd091971d541657024ffa9a1d1e7c9cc48a47ea> I shrunk a line.
  *   30c7341<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/30c73418af20d05f29918b5063cb61c727b66db5> I split a really long line which refused to fit on the page.
  *   1073da2<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/1073da2dcf9bfbd30ec21b32bbd049e1d392b1bf> I tried to improve a sentence just a bit.
  *   79d081d<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/79d081d6e0552b1f5316c336a8c92fc2b9974aa8> I replaced a janky code environment with a possibly janky sentence.
  *   3a16fc8<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/3a16fc8da1e7439f1edebf4ed3667a528d0b8664> I added some parentheses and *very* slightly changed the wording.
  *   167c952<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/167c952ccd94e2a46c35e9e522b98c92611d1d0a> I replaced a slightly janky parenthetical with a footnote.
  *   a35fd1c<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/a35fd1c22f1a3d684ecfd89c5528ae57acb713c3> We are now using Unicode arrows.
  *   26039c8<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/26039c8b971e3f0fd63523b3143e5d493691e23d> I fixed up some inconsistent lambda expression spacing.
  *   9622d68<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/9622d6875ae35bba04ecc83b86b3f248f705be0e> I deleted an unnecessary type declaration.
  *   351f9f8<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/351f9f8cab1de2b97fab4685679644a82ee805ec> I generally fixed up a sentence.
  *   46882ae<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/46882ae37c3e5de1a4c89acc4f92c6bb6fe69e00> I LaTeXified yet another paragraph.
  *   c04cfc1<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/c04cfc1aabca88f64b7fc890ba0e8d0647858afe> I tried to fix up a list in a LaTeXy way.
  *   a4e5811<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/a4e581184bc1cfd4c281e8aabf3ef9e66d4fb3b7> I replaced "both" with "two". In this case, "two" could be interpreted as referring to the second item of the list.

File Changes

(2 files<https://github.com/onestruggler/short-intro-reflection/pull/4/files>)

  *   D ShortIntroReflection.agda<https://github.com/onestruggler/short-intro-reflection/pull/4/files#diff-4a68ca95ce3178482b289d7726f25c940c33eff3e496a450f9e354d8b310e9a0> (343)
  *   A ShortIntroReflection.lagda.tex<https://github.com/onestruggler/short-intro-reflection/pull/4/files#diff-97bb8a8be66b31baf27f3d53682edbf5852e826b70ddd426b647227fa0754728> (405)

Patch Links:

  *   https://github.com/onestruggler/short-intro-reflection/pull/4.patch
  *   https://github.com/onestruggler/short-intro-reflection/pull/4.diff

**Comment by onestruggler** [comment]
i will merge it soon. i will also keep two files there in case someone just want to quickly run it. i will also put a compiled pdf there in case someone just want to read it without setting upa  tex compiler.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: andrewchawk ***@***.***>
Sent: Tuesday, August 13, 2024 10:57:44 PM
To: onestruggler/short-intro-reflection ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [onestruggler/short-intro-reflection] Myriad Improvements (PR #4)

CAUTION: The Sender of this email is not from within Dalhousie.

Really, I just improved the wording and formatting and converted the document to a literate Agda LaTeX file.

The upside is readability.
The downside is that, at least on my system, literally every line is now credited to me. :-)

As ever, feel free to delete any changes which you dislike.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/onestruggler/short-intro-reflection/pull/4

Commit Summary

  *   e141623<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/e1416238e50971bf4109ece723c8c19352ed2d0a> I deleted some *seemingly*-redundant spaces.
  *   cb72150<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/cb72150de18afe2d8c3b2a0d654f45bb0338be84> I tried to improve the formatting.
  *   04ea515<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/04ea5155995b79377a49641b21b38c0ec1b0e493> I broke up some long lines.
  *   49e2b2d<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/49e2b2d85d3b5ece4741e1b5014670321376c94f> I reformatted a definition in the style of Haskell's formatting for long lists.
  *   3c5d4cc<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/3c5d4cca919cc9cf3b898daeaad914b213fadafa> I got rid of some unneeded hidden arguments.
  *   cd587b8<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/cd587b8c952b6ff03534362b56e4f422641f5f1c> I joined some sentence fragments into a single sentence. I did have to change the method of emphasis a bit, though.
  *   7c2ddec<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/7c2ddec9a095fddae6c302a52cf7b5d2e0effb0b> I added some spaces to increase overall consistency in formatting.
  *   458570f<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/458570f005b2e6ff1b0cd62b6d257ebcab93868e> I corrected some misspellings.
  *   92adcb0<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/92adcb0bfcecdb618dcf57db8d2f766a659f0d87> I rewrote a sentence. The change might be subjective, though.
  *   5177083<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/5177083f413eaff241c5f736826d857c02128f72> I think that this change improves skimmability.
  *   b088a84<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/b088a843cc394f1e5aa0471fbed859f6bb8ba030> I junked an "always". From experience, I know that some conversions can be pretty difficult.
  *   43b15aa<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/43b15aa6886d618941e3221328d9480b952c3e01> I shrank a line.
  *   6b25042<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/6b2504222cd9f05109107e70411c25dc3445d4d2> I made myriad assorted documentation improvements.
  *   ab71c3f<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/ab71c3fd775e077417f386a665e65a2b57b265a7> I made myriad wording improvements.
  *   196e3b4<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/196e3b4e96b301bdb696f95a399d95bac37fb26b> I combined two words in a pseudo-type-signature. Semantically, "arithmetic expression" is kind of interesting, but I think that "ArithmeticExpression" is more straightforward. :-)
  *   e638b42<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/e638b422ce4a0362491555df0ec16c3a7ce7bdc8> I fixed up a comma splice.
  *   4923f3e<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/4923f3e0724ac367b9970d5534298edd412a428b> I made some general readability-related improvements.
  *   477e187<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/477e18768ed5f058d69cb1a02a59c6e287315e80> I tried to grammatically fix up a sentence, but I *may* have lost some of the tone of the original sentence.
  *   54f7a63<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/54f7a637043e33ec5d802241137f4eb400051a47> I applied a bunch of tiny changes to a single paragraph.
  *   0beabed<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/0beabed2c5817020bb817d01b361bbe047b31201> I replaced some assumption-related sentences with definition-related sentences.
  *   a4101ce<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/a4101cea99f2fec251fcb4c0c98cee43d7c3d7a0> I added a "then" and fixed some typos.
  *   576757b<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/576757ba1eef543275a9e0dce74f02bd6ffc61fa> I fixed up a sentence.
  *   24a0523<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/24a05231333ac13274861df5939d16b99687bc43> Revert "I combined two words in a pseudo-type-signature. Semantically, "arithmetic expression" is kind of interesting, but I think that "ArithmeticExpression" is more straightforward. :-)"
  *   f304c49<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/f304c49b6f00c5ba46b521cc522ce576f9d34e57> So begins the LaTeXification.
  *   1ec9f96<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/1ec9f96789de8cecd4e27038df420954861db4b3> I converted a one-line list into a multi-line list and made some minor wording improvements.
  *   cb571cd<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/cb571cd7179281854818ec6c5283e27f59db4007> I capitalized "Agda".
  *   8b7e96e<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/8b7e96e8b9059e5fea6b2ce2fabcc652e8ab195c> I tried to improve the readability of a segment.
  *   58ad553<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/58ad55312279aa08a8c94053d9b9c28a81709b70> I made some minor wording improvements.
  *   efcbadc<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/efcbadcb4a048ceb311f052b2a0ec706157386da> I issued a typo fix.
  *   8bd0919<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/8bd091971d541657024ffa9a1d1e7c9cc48a47ea> I shrunk a line.
  *   30c7341<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/30c73418af20d05f29918b5063cb61c727b66db5> I split a really long line which refused to fit on the page.
  *   1073da2<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/1073da2dcf9bfbd30ec21b32bbd049e1d392b1bf> I tried to improve a sentence just a bit.
  *   79d081d<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/79d081d6e0552b1f5316c336a8c92fc2b9974aa8> I replaced a janky code environment with a possibly janky sentence.
  *   3a16fc8<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/3a16fc8da1e7439f1edebf4ed3667a528d0b8664> I added some parentheses and *very* slightly changed the wording.
  *   167c952<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/167c952ccd94e2a46c35e9e522b98c92611d1d0a> I replaced a slightly janky parenthetical with a footnote.
  *   a35fd1c<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/a35fd1c22f1a3d684ecfd89c5528ae57acb713c3> We are now using Unicode arrows.
  *   26039c8<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/26039c8b971e3f0fd63523b3143e5d493691e23d> I fixed up some inconsistent lambda expression spacing.
  *   9622d68<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/9622d6875ae35bba04ecc83b86b3f248f705be0e> I deleted an unnecessary type declaration.
  *   351f9f8<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/351f9f8cab1de2b97fab4685679644a82ee805ec> I generally fixed up a sentence.
  *   46882ae<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/46882ae37c3e5de1a4c89acc4f92c6bb6fe69e00> I LaTeXified yet another paragraph.
  *   c04cfc1<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/c04cfc1aabca88f64b7fc890ba0e8d0647858afe> I tried to fix up a list in a LaTeXy way.
  *   a4e5811<https://github.com/onestruggler/short-intro-reflection/pull/4/commits/a4e581184bc1cfd4c281e8aabf3ef9e66d4fb3b7> I replaced "both" with "two". In this case, "two" could be interpreted as referring to the second item of the list.

File Changes

(2 files<https://github.com/onestruggler/short-intro-reflection/pull/4/files>)

  *   D ShortIntroReflection.agda<https://github.com/onestruggler/short-intro-reflection/pull/4/files#diff-4a68ca95ce3178482b289d7726f25c940c33eff3e496a450f9e354d8b310e9a0> (343)
  *   A ShortIntroReflection.lagda.tex<https://github.com/onestruggler/short-intro-reflection/pull/4/files#diff-97bb8a8be66b31baf27f3d53682edbf5852e826b70ddd426b647227fa0754728> (405)

Patch Links:

  *   https://github.com/onestruggler/short-intro-reflection/pull/4.patch
  *   https://github.com/onestruggler/short-intro-reflection/pull/4.diff

**Comment by andrewchawk** [comment]
> as long as it's improvement for others, i don't care credit at all.

You might like the Unlicense.

**Comment by onestruggler** [comment]
Hi Anrew,

I saw you have made lots of improvements, and I think you should take credit for that. So, I added your name to the author and license.

As for unilicense, I think it is too "open", let's maybe keep the current license.

Also, can you help check if the pdf file generated by me is the same as yours? The pdf file is in the repo now.

Thanks a lot for the hard work!

Best,
Xiaoning Bian
________________________________

**Comment by andrewchawk** [comment]
> I saw you have made lots of improvements, and I think you should take credit for that. So, I added your name to the author and license.

D'aww.  Thank you.
You screwed up my name, though, which is understandable.  From your e-mail address, I actually thought that your name was "Ian B.".  I have no room to judge.  :-)

> As for unilicense, I think it is too "open", let's maybe keep the current license.

What is the working definition of "open"?  Per my understanding, the only major difference between the Unlicense and the MIT license is that the MIT license requires attribution, but you have said that you do not care about such attribution.

> Also, can you help check if the pdf file generated by me is the same as yours?

Everything looks good to me.

Also, regarding having two Agda files, I strongly recommend deleting the plain ".agda" file; having *both* files confuses agda-mode(1), and, as indicated by the following snippet, agda(1) can quickly check .agda.tex files.  I actually had to delete the plain ".agda" file when I recently made some more changes.

```
slim$ /home/ach/.local/bin/agda ShortIntroReflection.lagda.tex  
Checking ShortIntroReflection (/home/ach/prog-ram/short-intro-reflection/ShortIntroReflection.lagda.tex).
slim$ ls -l ShortIntroReflection.agdai                                               
-rw-r--r--  1 ach  ach  138337 Aug 14 12:46 ShortIntroReflection.agdai
```

**Comment by onestruggler** [comment]
as for the .agda file, how about we change the file name of it? say to ShortIntroReflectionCode.agda?

as for license, I still care a little bit. Sorry that I was saying that I don't care at all. What I meant to say is I don't mind sharing credit with others at all. I still want some credit for myself and for my collabrators.

as for collabrations and names. First of all, you are welcome and thanks to you, and you deserve it.
At least I got your first name right :)
Nice to meet your Andrew Christopher Hawk! The other Hawk I know is from Marvel movie. There are Andrew and Christopher (both are first names) in our research group when I was a graduate student.

**Pull request merged**
